In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from Linear_Model.linear_regression import Linear_Regression

In [2]:
# Load our data set
x_train = np.array([1.0, 2.0])   #features
y_train = np.array([300.0, 500.0])   #target value

In [3]:
x_train.shape[0]

2

In [4]:
lr = Linear_Regression()

In [5]:
lr.compute_cost(x_train, y_train, w_init, b_init)

NameError: name 'w_init' is not defined

In [8]:
# initialize parameters
w_init = 0
b_init = 0
# some gradient descent settings
iterations = 10000
tmp_alpha = 1.0e-2
# run gradient descent
w_final, b_final, J_hist, p_hist = lr.gradient_descent(x_train, 
                                                       y_train, 
                                                       w_init, 
                                                       b_init, 
                                                       tmp_alpha, 
                                                       iterations
                                                      )
print(f"(w,b) found by gradient descent: ({w_final:8.4f},{b_final:8.4f})")

Iteration    0: Cost 7.93e+04 djdw: -6.500e+02, djdb: -4.000e+02 w:  6.500e+00, b:  4.00000e+00
Iteration  1000: Cost 3.41e+00 djdw: -3.712e-01, djdb:  6.007e-01 w:  1.949e+02, b:  1.08228e+02
Iteration  2000: Cost 7.93e-01 djdw: -1.789e-01, djdb:  2.895e-01 w:  1.975e+02, b:  1.03966e+02
Iteration  3000: Cost 1.84e-01 djdw: -8.625e-02, djdb:  1.396e-01 w:  1.988e+02, b:  1.01912e+02
Iteration  4000: Cost 4.28e-02 djdw: -4.158e-02, djdb:  6.727e-02 w:  1.994e+02, b:  1.00922e+02
Iteration  5000: Cost 9.95e-03 djdw: -2.004e-02, djdb:  3.243e-02 w:  1.997e+02, b:  1.00444e+02
Iteration  6000: Cost 2.31e-03 djdw: -9.660e-03, djdb:  1.563e-02 w:  1.999e+02, b:  1.00214e+02
Iteration  7000: Cost 5.37e-04 djdw: -4.657e-03, djdb:  7.535e-03 w:  1.999e+02, b:  1.00103e+02
Iteration  8000: Cost 1.25e-04 djdw: -2.245e-03, djdb:  3.632e-03 w:  2.000e+02, b:  1.00050e+02
Iteration  9000: Cost 2.90e-05 djdw: -1.082e-03, djdb:  1.751e-03 w:  2.000e+02, b:  1.00024e+02
(w,b) found by gradient descent

In [9]:
f_wb = lr.predict(x_train, w_init, b_init)

In [10]:
f_wb

array([0., 0.])

In [12]:
f_wb - y_train

array([-300., -500.])

In [13]:
(f_wb - y_train) * x_train

array([ -300., -1000.])

In [14]:
((f_wb - y_train) * x_train).mean()

-650.0

In [15]:
np.mean((f_wb - y_train) * x_train)

-650.0